[workspace]
members = [
    "aoc*",
    "utils",
]

[profile.release]
debug = true

[workspace.dependencies]
anyhow = "1.0"
cached = "0.26"
itertools = "0.10"
lazy_static = "1.4"
md5 = "0.7"
nom = "7.1.1"
regex = "1.4"
serde_json = "1.0"
utils = { path = "utils" }
